In [1]:
#  Ebnable HTML/CSS 
from IPython.core.display import HTML
HTML("<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'><style>div.attn { font-family: 'Helvetica Neue'; font-size: 30px; line-height: 40px; color: #FFFFFF; text-align: center; margin: 30px 0; border-width: 10px 0; border-style: solid; border-color: #5AAAAA; padding: 30px 0; background-color: #DDDDFF; }hr { border: 0; background-color: #ffffff; border-top: 1px solid black; }hr.major { border-top: 10px solid #5AAA5A; }hr.minor { border: none; background-color: #ffffff; border-top: 5px dotted #CC3333; }div.bubble { width: 65%; padding: 20px; background: #DDDDDD; border-radius: 15px; margin: 0 auto; font-style: italic; color: #f00; }em { color: #AAA; }div.c1{visibility:hidden;margin:0;height:0;}div.note{color:red;}</style>")

___
Enter Team Member Names here (double click to edit):

- Name 1: Andy Ho
- Name 2: Samira Zarandioon
- Name 3: Jaime Villanueva
- Name 3: Tori Wheelis

# In Class Assignment One
In the following assignment you will be asked to fill in python code and derivations for a number of different problems. Please read all instructions carefully and turn in the rendered notebook (or HTML of the rendered notebook)  before the end of class (or right after class). The initial portion of this notebook is given before class and the remainder is given during class. Please answer the initial questions before class. Once class has started you may rework your answers as a team for the initial part of the assignment. 

<a id="top"></a>
## Contents
* <a href="#Loading">Loading the Data</a>
* <a href="#linearnumpy">Linear Regression</a>
* <a href="#sklearn">Using Scikit Learn for Regression</a>
* <a href="#classification">Linear Classification</a>

________________________________________________________________________________________________________

<a id="Loading"></a>
<a href="#top">Back to Top</a>
## Loading the Data
Please run the following code to read in the "diabetes" dataset from sklearn's data loading module. 

This will load the data into the variable `ds`. `ds` is a dictionary object with fields like `ds.data`, which is a matrix of the continuous features in the dataset. The object is not a pandas dataframe. It is a numpy matrix. Each row is a set of observed instances, each column is a different feature. It also has a field called `ds.target` that is a continuous value we are trying to predict. Each entry in `ds.target` is a label for each row of the `ds.data` matrix. 

In [2]:
from __future__ import print_function
from sklearn.datasets import load_diabetes
import numpy as np

ds = load_diabetes()

# this holds the continuous feature data
# because ds.data is a matrix, there are some special properties we can access (like 'shape')
print('features shape:', ds.data.shape, 'format is:', ('rows','columns')) # there are 442 instances and 10 features per instance
print('range of target:', np.min(ds.target),np.max(ds.target))

features shape: (442, 10) format is: ('rows', 'columns')
range of target: 25.0 346.0


In [3]:
from pprint import pprint

# we can set the fields inside of ds and set them to new variables in python
pprint(ds.data) # prints out elements of the matrix
pprint(ds.target) # prints the vector (all 442 items)

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])
array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37

________________________________________________________________________________________________________
<a id="linearnumpy"></a>
<a href="#top">Back to Top</a>
## Using Linear Regression 
In the videos, we derived the formula for calculating the optimal values of the regression weights (you must be connected to the internet for this equation to show up properly):

$$ w = (X^TX)^{-1}X^Ty $$

where $X$ is the matrix of values with a bias column of ones appended onto it. For the diabetes dataset one could construct this $X$ matrix by stacking a column of ones onto the `ds.data` matrix. 

$$ X=\begin{bmatrix}
         & \vdots &        &  1 \\
        \dotsb & \text{ds.data} & \dotsb &  \vdots\\
         & \vdots &         &  1\\
     \end{bmatrix}
$$

**Question 1:** For the diabetes dataset, how many elements will the vector $w$ contain?

In [4]:
# Enter your answer here (or write code to calculate it)

#selecting the element at first index and add by 1 for the column of 1's
elements = ds.data.shape[1] + 1
print('Question 1: Vector w has', elements, 'elements.')

Question 1: Vector w has 11 elements.


#### Question 1: For the diabetes dataset, how many elements will the vector 𝑤 contain?

Answer: 11

________________________________________________________________________________________________________

**Exercise 1:** In the following empty cell, use this equation and numpy matrix operations to find the values of the vector $w$. You will need to be sure $X$ and $y$ are created like the instructor talked about in the video. Don't forget to include any modifications to $X$ to account for the bias term in $w$. You might be interested in the following functions:

- `np.hstack((mat1,mat2))` stack two matrices horizontally, to create a new matrix
- `np.ones((rows,cols))` create a matrix full of ones
- `my_mat.T` takes transpose of numpy matrix named `my_mat`
- `np.dot(mat1,mat2)` is matrix multiplication for two matrices
- `np.linalg.inv(mat)` gets the inverse of the variable `mat`

In [5]:
# Write you code here, print the values of the regression weights using the 'print()' function in python

y = ds.target
X = ds.data

bias = np.ones((len(ds.target),1)) #create column of 1's
X = np.hstack((ds.data, bias))     #stick column of ones onto data matrix


w = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y) # applying the formula for the weights w

print("Regression Weights:")
print(np.round(w, 2))

Regression Weights:
[ -10.01 -239.82  519.84  324.39 -792.18  476.75  101.04  177.06  751.28
   67.63  152.13]



___
<a id="sklearn"></a>
<a href="#top">Back to Top</a>
# Start of Live Session Coding

**Exercise 2:** Scikit-learn also has a linear regression fitting implementation. Look at the scikit learn API and learn to use the linear regression method. The API is here: 

- API Reference: http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

Use the sklearn `LinearRegression` module to check your results from the previous question. 

**Question 2**: Did you get the same parameters? 

In [6]:
from sklearn.linear_model import LinearRegression as LR

#Produce weights using LinearRegression from sklearn
lr = LR(fit_intercept=False).fit(X, y)
lr_int = LR().fit(X, y) # created so intercept will properly show with lr_int.intercept_

print('model coefficients are:', np.round(lr.coef_, 2))
print('model intercept is', np.round(lr_int.intercept_))
print('Answer to question is', 'yes')

model coefficients are: [ -10.01 -239.82  519.84  324.39 -792.18  476.75  101.04  177.06  751.28
   67.63  152.13]
model intercept is 152.0
Answer to question is yes


#### Question 2: Did you get the same parameters? 
Answer: yes

________________________________________________________________________________________________________

Recall that to predict the output from our model, $\hat{y}$, from $w$ and $X$ we need to use the following formula:

- $\hat{y}=w^TX^T$

Where $X$ is a matrix with example instances in *each row* of the matrix. 

**Exercise 3:** 
- *Part A:* Use matrix multiplication to predict output using numpy, $\hat{y}_{numpy}$ and also using the sklearn regression object, $\hat{y}_{sklearn}$.
 - **Note**: you may need to make the regression weights a column vector using the following code: `w = w.reshape((len(w),1))` This assumes your weights vector is assigned to the variable named `w`.
- *Part B:* Calculate the mean squared error between your prediction from numpy and the target, $\sum_i(y-\hat{y}_{numpy})^2$. 
- *Part C:* Calculate the mean squared error between your sklearn prediction and the target, $\sum_i(y-\hat{y}_{sklearn})^2$.

In [7]:
#Part A
y_hat_np = np.dot(w.T, X.T)
y_hat_sklearn = lr.predict(X)

#Part B
mse_np = (np.square(y-y_hat_np).sum())/X.shape[0]
print('MSE numpy is: ' + str(np.round(mse_np, 2)))

#Part C
mse_sklearn = (np.square(y-y_hat_sklearn).sum())/X.shape[0]
print('MSE SKlearn is: ' + str(np.round(mse_sklearn, 2)))

MSE numpy is: 2859.69
MSE SKlearn is: 2859.69


________________________________________________________________________________________________________
<a id="classification"></a>
<a href="#top">Back to Top</a>
## Using Linear Classification
Now lets use the code you created to make a classifier with linear boundaries. Run the following code in order to load the iris dataset.

In [8]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LinearRegression as LR
import numpy as np

# this will overwrite the diabetes dataset
ds = load_iris()
print('features shape:', ds.data.shape) # there are 150 instances and 4 features per instance
print('original number of classes:', len(np.unique(ds.target)))

# now let's make this a binary classification task
ds.target = ds.target>1
print ('new number of classes:', len(np.unique(ds.target)))

features shape: (150, 4)
original number of classes: 3
new number of classes: 2


________________________________________________________________________________________________________

**Exercise 4:** Now use linear regression to come up with a set of weights, `w`, that predict the class value. This is exactly like you did before for the *diabetes* dataset. However, instead of regressing to continuous values, you are just regressing to the integer value of the class (0 or 1), like we talked about in the video. Remember to account for the bias term when constructing the feature matrix, `X`. Print the weights of the linear classifier.

In [9]:
# code to get value of weights for iris set 
y = ds.target
X = ds.data

bias = np.ones([len(X), 1])
X = np.hstack((X, bias))

w = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y)
print("The set of continuous weights using numpy is:")
print('\t' +  str(w) + '\n')

lr = LR(fit_intercept=False).fit(X, y) # get weights using sklearn linear regression for comparison
print("The set of continuous weights using sklearn is: ")
print('\t' + str(lr.coef_))

The set of continuous weights using numpy is:
	[-0.04587608  0.20276839  0.00398791  0.55177932 -0.69528186]

The set of continuous weights using sklearn is: 
	[-0.04587608  0.20276839  0.00398791  0.55177932 -0.69528186]


________________________________________________________________________________________________________

**Exercise 5:** Finally, use a hard decision function on the output of the linear regression to make this a binary classifier. This is just like we talked about in the video, where the output of the linear regression passes through a function: 

- $\hat{y}=g(w^TX^T)$ where
 - $g(w^TX^T)$ for $w^TX^T < \alpha$ maps the predicted class to `0` 
 - $g(w^TX^T)$ for $w^TX^T \geq \alpha$ maps the predicted class to `1`. 

Here, alpha is a threshold for deciding the class. 

**Question 3**: What value for $\alpha$ makes the most sense? What is the accuracy of the classifier given the $\alpha$ you chose? 

Note: You can calculate the accuracy with the following code: `accuracy = float(sum(yhat==y)) / len(y)` assuming you choose variable names `y` and `yhat` for the target and prediction, respectively.

In [10]:
#Binarize the predicted output and get accuracy score

#Generate predicted for weights using numpy
y_hat = np.dot(w, X.T)

#Function comparator takes numerical input and forces it to a high or low value based on alpha
def comparator(input, alpha, low_val, high_val): 
    return low_val if input < alpha  else high_val

#find optimal alpha by by checking accuracy
for alpha in np.arange(0, 1, .01):
    print("alpha: ", alpha)
    y_hat_binarized = []
    for x in y_hat:
        result = comparator(x, alpha, False, True)
        y_hat_binarized.append(result)
    accuracy = float(sum(y_hat_binarized==y)) / len(y)
    print('Percentage accuracy:', accuracy)


alpha:  0.0
Percentage accuracy: 0.6066666666666667
alpha:  0.01
Percentage accuracy: 0.6066666666666667
alpha:  0.02
Percentage accuracy: 0.62
alpha:  0.03
Percentage accuracy: 0.6266666666666667
alpha:  0.04
Percentage accuracy: 0.6266666666666667
alpha:  0.05
Percentage accuracy: 0.6466666666666666
alpha:  0.06
Percentage accuracy: 0.6466666666666666
alpha:  0.07
Percentage accuracy: 0.6533333333333333
alpha:  0.08
Percentage accuracy: 0.6666666666666666
alpha:  0.09
Percentage accuracy: 0.6666666666666666
alpha:  0.1
Percentage accuracy: 0.6666666666666666
alpha:  0.11
Percentage accuracy: 0.68
alpha:  0.12
Percentage accuracy: 0.68
alpha:  0.13
Percentage accuracy: 0.6866666666666666
alpha:  0.14
Percentage accuracy: 0.7
alpha:  0.15
Percentage accuracy: 0.7
alpha:  0.16
Percentage accuracy: 0.7066666666666667
alpha:  0.17
Percentage accuracy: 0.72
alpha:  0.18
Percentage accuracy: 0.7266666666666667
alpha:  0.19
Percentage accuracy: 0.7266666666666667
alpha:  0.2
Percentage accur

##### Question 3: What value for 𝛼 makes the most sense? What is the accuracy of the classifier given the 𝛼 you chose?
The value of alpha that makes the most sense for this particular set is one that predicts the actual output with the best accuracy.<br>

**best result:** alpha = 0.52 gives an accuracy of 94.7%

**note:** Since there is no cross-validation, result probably will not generalize

________________________________________________________________________________________________________

That's all! Please **save (make sure you saved!!!) and upload your rendered notebook** and please include **team member names** in the notebook submission.